### ISSUE TITLE
Bad indent of encryption: key in config.yaml

### ISSUE THREAD

**Issue by marcinkoziej** [nathanael-h/mautrix_googlechat_ynh#1]
https://github.com/nathanael-h/mautrix_googlechat_ynh/blob/7280710bed86864611e261bf661e784c09ec217c/conf/config.yaml#L129C4-L129C9

**Comment by nathanael-h** [comment]
Thanks, fixed in #4 see actual line in master: https://github.com/nathanael-h/mautrix_googlechat_ynh/blob/73c2ece82fd2fbe5b1015efb29ae6fa902a2753b/conf/config.yaml#L131
