### ISSUE TITLE
Update to 0.5.0

### ISSUE THREAD

**Issue by marcinkoziej** [nathanael-h/mautrix_googlechat_ynh#3]
Hey,
I was no longer able to log in using old method, but after [updating to 0.5.0](https://github.com/nathanael-h/mautrix_googlechat_ynh/commit/d4cbea3230f56211d0eedbc23edee4a82594f5e7) this bridge works with ynh!

Not sure what's the proper way to upgrade manifest.json in terms of version... What would you suggest?

**Comment by nathanael-h** [comment]
We have to verify that the file https://github.com/nathanael-h/mautrix_googlechat_ynh/blob/master/conf/config.yaml is in sync with the template upstream https://github.com/mautrix/googlechat/blob/master/mautrix_googlechat/example-config.yaml

**Comment by nathanael-h** [comment]
I created a PR for that: https://github.com/nathanael-h/mautrix_googlechat_ynh/pull/4 
Can you test it with `sudo yunohost app upgrade mautrix_googlechat -u https://github.com/nathanael-h/mautrix_googlechat_ynh/tree/v0.5.0 --debug` ?

**Comment by nathanael-h** [comment]
https://github.com/nathanael-h/mautrix_googlechat_ynh/pull/4 was merged
