### ISSUE TITLE
Archive the project?

### ISSUE THREAD

**Issue by selfhoster1312** [nathanael-h/mautrix_googlechat_ynh#5]
Hello!

Is this package still maintained? It references backports to Debian buster (oldoldstable), and [Matrix's libolm has been entirely deprecated](https://matrix.org/blog/2024/08/libolm-deprecation/) to be replaced by their Rust implementation.

**Comment by nathanael-h** [comment]
Hello, this package is not actually maintained. On my side I don't use Google Chat anymore and thus cannot even test it for real.

**Comment by nathanael-h** [comment]
But as [upstream](https://github.com/mautrix/googlechat) is still maintained someone could update this repo. For now, this app is not listed in [Yunohost catalog.](https://apps.yunohost.org/catalog?search=google). Thus I don't think we should archive this repo.
